name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          export VERSION=$(awk '/version =/{print $NF}' build.gradle | tr -d "'")
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-discovery:$VERSION .
          docker push ${{ secrets.DOCKER_REPO }}//service-discovery:$VERSION
