name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## gradle test
      - name: Test with Gradle
        run: ./gradlew test --stacktrace

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar --stacktrace -x test

      - name: Get Version, Name
        id: get-version-name
        run: |
          export APPLICATION_NAME=$(yq e '.spring.application.name' ./src/main/resources/application.yml)
          export VERSION=$(awk '/version =/{print $NF}' build.gradle | tr -d "'")
          echo "APPLICATION_NAME=$APPLICATION_NAME" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: dockerfile-arm
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ steps.get-version-name.outputs.APPLICATION_NAME }}:${{ steps.get-version-name.outputs.VERSION }}-arm
          platforms: |
            linux/arm/v8
